<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Verify Email</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body style="background-color: cornsilk">
    <table cellpadding="0" cellspacing="0" style="width: 100%; border: 0;">
        <tr>
            <td style="align-items: center; background-color: cornsilk;">
                <table border="0" cellpadding="0" cellspacing="0" style="max-width: 600px; width: 100%">
                    <tr>
                        <td valign="top" style="padding: 36px 24px; align-items: center"></td>
                    </tr>
                </table>
                </td>
                </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td align="center" bgcolor="#e9ecef">
                <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                    <tr>
                        <td valign="top" style="align-items: center; width: 600px">
                <table border="0" cellpadding="0" cellspacing="0" style="max-width: 600px; width: 100%">
                    <tr>
                        <td align="left" bgcolor="#ffffff"
                            style="padding: 36px 24px 0; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; border-top: 3px solid #d4dadf;">
                            <h1 style="margin: 0; font-size: 32px; font-weight: 700; letter-spacing: -1px; line-height: 48px;">
                                Verify your email
                            </h1>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td style="align-items: center; background-color: cornsilk">
                <table style="width: 100%; max-width: 600px" cellspacing="0" border="0" cellpadding="0">
                    <tr>
                        <td align="left" style="background-color: #ffffff; padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;">
                            <p style="margin: 0;">
                                Please submit your verification code after receiving this notification
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td align="left" style="background-color: white">
                            <table border="0" cellpadding="0" cellspacing="0" style="width: 100%">
                                <tr>
                                    <td align="center" bgcolor="#ffffff" style="padding: 12px;">
                                        <table border="0" cellpadding="0" cellspacing="0">
                                            <tr>
                                                <td align="center" bgcolor="#1a82e2" style="border-radius: 6px;">
                                                    <div style="display: inline-block; padding: 16px 36px; font-family: Tahoma,sans-serif; font-size: 26px; color: white; font-weight: bold; text-decoration: none; border-radius: 6px;">
                                                        <span>${token}</span>
                                                    </div>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table
    >
</body>
</html>